name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to create'     
        required: true

jobs:
  build_and_test:
    runs-on: macos-latest
    name: Build and test on macOS
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          include-prerelease: true
      
      - name: Install UPX
        run: brew install upx
      
      - name: Build Package (CI)
        if: ${{ github.event.inputs.version == '' }}
        run: |
          dotnet build -t:Pack src/PublishAotCompressed.macOS.nuproj
      
      - name: Test - Build for macOS (should skip UPX)
        if: ${{ github.event.inputs.version == '' }}
        run: |
          dotnet publish -r osx-arm64 -c Release test/Hello.csproj
          ls -lh test/bin/Release/net9.0/osx-arm64/publish/
      
      - name: Build Package (CD)
        if: ${{ github.event.inputs.version != '' }}
        run: dotnet build -t:Pack src/PublishAotCompressed.macOS.nuproj -p:Version=${{ github.event.inputs.version }}
      
      - name: Archive NuGet Package
        if: ${{ github.event.inputs.version != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: PublishAotCompressed.macOS.${{ github.event.inputs.version }}.nupkg
          path: src/bin/Debug/PublishAotCompressed.macOS.${{ github.event.inputs.version }}.nupkg
      
      - name: Create Release Tag
        if: ${{ github.event.inputs.version != '' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag v${{ github.event.inputs.version }}
          git push origin v${{ github.event.inputs.version }}
